import { Routes } from "@angular/router";

import { HomeComponent } from "../home/home.component";
import { UserProfileComponent } from "../user-profile/user-profile.component";
import { ReportsComponent } from "../reports/reports.component";
import { RequestsComponent } from "app/requests/requests.component";
import { MyPropertiesComponent } from "app/myProperties/my_properties.component";
import { AppointmentsComponent } from "app/appointments/appointments.component";
import { DocumentsComponent } from "app/documents/documents.component";
import { NewPaymentComponent } from "app/new_payment/new_payment.component";
import { FM_MaintananceRequest } from "app/indus_services/facility_management/fm-maintanence_request/fm-maintanence_request.component";
import { Tenant_Move_out_Request } from "app/indus_services/facility_management/tenant_move-out_request/tenant_move-out_request.component";
import { PageNotFoundComponent } from "app/404_page_not_found/404_page_not_found.component";
import { AddPropertyForm } from "app/add-property-form/add_property_from";
import { AdminRequests } from "app/admin-requests/admin-requests";
import { PropertyPage } from "app/property-page/property-page.component";
import { AdminDashboardComponent } from "app/admin_dashboard/admin_dashboard";
import { LoginComponent } from "app/login/login.component";
import { RegisterComponent } from "app/register/register.component";
import { LandlordFormComponent } from "app/landlord_register_form/landlord_form.component";
import { TenantRegisterComponent } from "app/indus_services/facility_management/tenant_register_form/tenant_form.component";
import { RequestPage } from "app/request-page/request-page";
import { AdminTenantClients } from "app/admin_tenant_clients/admin_tenant_clients";
import { AdminLandlordClients } from "app/admin_landlord_clients/admin_landlord_clients";
import { AdminSaleProperties } from "app/admin_sale_properties/admin_sale_properties";
import { AdminRentProperties } from "app/admin_rent_properties/admin_rent_properties";
import { CustomerCareComponent } from "app/indus_services/customer_service/customer_care";
import { Tenant_Move_in_Request } from "app/indus_services/facility_management/tenant_move-in_request/tenant_move-in_request";
import { PaymentRecapComponent } from "app/payment_recap/payment_recap";

export const AdminLayoutRoutes: Routes = [
  { path: "home", component: HomeComponent },
  { path: "user-profile", component: UserProfileComponent },
  { path: "reports", component: ReportsComponent },
  { path: "requests", component: RequestsComponent },
  { path: "my-properties", component: MyPropertiesComponent },
  { path: "appointments", component: AppointmentsComponent },
  { path: "documents", component: DocumentsComponent },
  { path: "new-payment", component: NewPaymentComponent },
  { path: "fm-maintanence-request", component: FM_MaintananceRequest },
  { path: "tenant-move-out-request", component: Tenant_Move_out_Request },
  { path: "tenant-move-in-request", component: Tenant_Move_in_Request },
  { path: "property-page", component: PropertyPage },
  { path: "request-page", component: RequestPage },
  { path: "add-property-form", component: AddPropertyForm },
  // admin pages
  { path: "admin-dashboard", component: AdminDashboardComponent },
  { path: "admin-requests", component: AdminRequests },
  { path: "login", component: LoginComponent },
  { path: "register", component: RegisterComponent },
  { path: "landlord-register-form", component: LandlordFormComponent },
  { path: "tenant-register-form", component: TenantRegisterComponent },
  { path: "admin-tenant-clients", component: AdminTenantClients },
  { path: "admin-landlord-clients", component: AdminLandlordClients },
  { path: "admin-properties-sale", component: AdminSaleProperties },
  { path: "admin-properties-rent", component: AdminRentProperties },
  { path: "customer-care", component: CustomerCareComponent },
  { path: "payment-recap", component: PaymentRecapComponent },
  { path: "404", component: PageNotFoundComponent },
  { path: "**", redirectTo: "/404" },
];
